### ISSUE TITLE
Question: Is there a way to add multiple getters/setters at once?

### ISSUE THREAD

**Issue by leo-rojas** [r4ven1245/vscode-php-getter-setter#10]
Was just wondering if there was a way to insert getters for all properties at once rather than one at a time?

Thanks for this extension!

**Comment by r4ven1245** [comment]
Yes, VSCode has a built-in feature to put multiple cursors
Hold alt and click on the place you want the cursor to be
You can do this as much as you want. And as long as you place all cursors on the variable name, you can then use the keyboard shortcut to add getters and setters (Ctrl+Alt+G by default)
It would then place them in the order that you placed cursors, and not in the order that they are located in the document
