### ISSUE TITLE
Insert getter/setter in a namespaced class places the functions outside the class

### ISSUE THREAD

**Issue by emilnymann** [r4ven1245/vscode-php-getter-setter#3]
When adding a getter/setter to a property in a class with a declared namespace, the resulting getter and setter functions are placed outside the closing bracket of the class declaration, presumable because this extension goes by the last closing bracket, which in this case is that of the namespace declaration and not the class.

Example given:
Take a class declaration of _Layout_ placed inside a namespace declaration of _wpeconomic_.
![image](https://user-images.githubusercontent.com/27289912/124499609-9c419300-ddbe-11eb-9176-a636e1bfd90e.png)

Use the _Insert PHP 8 Getter and Setter_ command on one of its properties and the resulting functions are placed outside the closing bracket of the class declaration.
![image](https://user-images.githubusercontent.com/27289912/124499796-eb87c380-ddbe-11eb-97f9-21a9c9cfab6d.png)

**Comment by r4ven1245** [comment]
Fixed in release 1.1.1
